[package]
name = "cargo-leptos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.9"
anyhow = "1.0"
log = "0.4"
simplelog = { version = "0.12", features = ["paris"] }
lightningcss = { version = "1.0.0-alpha.36", features = ["browserslist"] }
browserslist-rs = "0.12"
tokio = { version = "1", default-features = false, features = ["full"] }
axum = "0.5"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.3", features = ["fs"] }
glob = "0.3"
notify = "5.0"
