[package]
name = "cargo-leptos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.9"
thiserror = "1.0"
log = "0.4"
simplelog = { version = "0.12", features = ["paris"] }
xshell = "0.2"
lightningcss = { version = "1.0.0-alpha.36", features = ["browserslist"] }
browserslist-rs = "0.12"
