[leptos]
root = "example/"
# path, relative to root, to generat rust code to
gen_path = "src/server/generated.rs"
# path, relative to root, to the index.html file
index_path = "index.html"

[leptos.style]
file = "style/main.scss"
# A https://browsersl.ist query
browserquery = "defaults"
