[leptos]
# root path, all following paths are relative to this
root = "./"
# path to generate rust code to
gen_path = "src/server/generated.rs"
# path to the index.html file
index_path = "index.html"

[leptos.style]
file = "style/main.scss"
# A https://browsersl.ist query
browserquery = "defaults"
