[leptos]
app_path = "app"
client_path = "client"
server_path = "server"
index_path = "app/index.html"
# path to generated rust code
gen_path = "app/src/generated.rs"

[leptos.style]
files = ["app/style/main.scss"]
# A https://browsersl.ist query
browserquery = "defaults"
